version: '3.9'
services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
  backend:
    build: ./backend
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
      - PORT=8080
    depends_on:
      - redis
  frontend:
    build: ./frontend
    ports:
      - 3000:3000